//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Api;
using Controls.Alert;
using Controls.Button;
using Controls.CheckBox;
using Controls.Container;
using Controls.Container.Extentions;
using Controls.Editors.DateSelector;
using Controls.Editors.DropDown;
using Controls.Editors.EmailEdit;
using Controls.Editors.LinkEdit;
using Controls.Editors.Selector;
using Controls.Grid;
using Controls.Grid.Filter;
using Controls.Grid.Upload;
using Controls.GroupBox;
using Controls.Input.PXNumberEdit;
using Controls.Input.PXTextEdit;
using Controls.Label;
using Controls.PxControlCollection;
using Controls.RichTextEdit;
using Controls.ToolBarButton;
using Core;
using Core.ApiConnection;
using Core.Core.Browser;
using Core.Wait;
using System;


namespace WorkWaveIntegrationQA.Tests.Wrappers
{
    
    
    public class AR303020_CustomerLocationMaint : Wrapper
    {
        
        public Note NotePanel;
        
        public SmartPanel_AttachFile FilesUploadDialog;
        
        public PxToolBar ToolBar;
        
        protected c_location_frmheader Location_frmHeader { get; } = new c_location_frmheader("ctl00_phF_frmHeader", "Location_frmHeader");
        protected c_parameters_gridwizard Parameters_gridWizard { get; } = new c_parameters_gridwizard("ctl00_usrCaption_shareColumnsDlg_gridWizard", "Parameters_gridWizard");
        protected c_profilerinfoview_formprofiler ProfilerInfoView_formProfiler { get; } = new c_profilerinfoview_formprofiler("ctl00_usrCaption_pnlProfiler_formProfiler", "ProfilerInfoView_formProfiler");
        protected c_firstselect_formactions FirstSelect_FormActions { get; } = new c_firstselect_formactions("ctl00_usrCaption_CustomizationDialogs_PXSmartPanel1_FormActions", "FirstSelect_FormActions");
        protected c_comboboxvalues_gridcombos ComboBoxValues_gridCombos { get; } = new c_comboboxvalues_gridcombos("ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos", "ComboBoxValues_gridCombos");
        protected c_vieweleminfo_formeleminfo ViewElemInfo_FormElemInfo { get; } = new c_vieweleminfo_formeleminfo("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo", "ViewElemInfo_FormElemInfo");
        protected c_filterworkingproject_formnewproject FilterWorkingProject_FormNewProject { get; } = new c_filterworkingproject_formnewproject("ctl00_usrCaption_CustomizationDialogs_DlgNewProject_FormNewProject", "FilterWorkingProject_FormNewProject");
        protected c_filterworkingproject_formselectproject FilterWorkingProject_FormSelectProject { get; } = new c_filterworkingproject_formselectproject("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_FormSelectProject", "FilterWorkingProject_FormSelectProject");
        protected c_gridlist_gridgrid GridList_gridGrid { get; } = new c_gridlist_gridgrid("ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid", "GridList_gridGrid");
        protected c_userlist_usergrid UserList_userGrid { get; } = new c_userlist_usergrid("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid", "UserList_userGrid");
        protected c_userlist_lv0 UserList_lv0 { get; } = new c_userlist_lv0("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_lv0", "UserList_lv0");
        protected c_locationcurrent_tab LocationCurrent_tab { get; } = new c_locationcurrent_tab("ctl00_phG_tab", "LocationCurrent_tab");
        protected c_address_address Address_Address { get; } = new c_address_address("ctl00_phG_tab_t0_Address", "Address_Address");
        protected c_contact_contact Contact_Contact { get; } = new c_contact_contact("ctl00_phG_tab_t0_Contact", "Contact_Contact");
        protected c_araccountsublocation_araccountsublocation ARAccountSubLocation_ARAccountSubLocation { get; } = new c_araccountsublocation_araccountsublocation("ctl00_phG_tab_t2_ARAccountSubLocation", "ARAccountSubLocation_ARAccountSubLocation");
        protected c_araccountsublocation_araccountsublocation1 ARAccountSubLocation_ARAccountSubLocation1 { get; } = new c_araccountsublocation_araccountsublocation1("ctl00_phG_tab_t2_ARAccountSubLocation1", "ARAccountSubLocation_ARAccountSubLocation1");
        protected c_addresslookupfilter_addresslookuppanelformaddress AddressLookupFilter_AddressLookupPanelformAddress { get; } = new c_addresslookupfilter_addresslookuppanelformaddress("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress", "AddressLookupFilter_AddressLookupPanelformAddress");
        protected c_filterpreview_formpreview FilterPreview_FormPreview { get; } = new c_filterpreview_formpreview("ctl00_usrCaption_PanelDynamicForm_FormPreview", "FilterPreview_FormPreview");
        public c_attributes Attributes { get; } = new c_attributes("ctl00_phF_frmHeader_t1", "Attributes");
        
        public AR303020_CustomerLocationMaint()
        {
            ScreenId = "AR303020";
            ScreenUrl = "/Pages/AR/AR303020.aspx";
            NotePanel = new Note("ctl00_usrCaption_tlbDataView");
            FilesUploadDialog = new SmartPanel_AttachFile("ctl00_usrCaption_tlbDataView");
            ToolBar = new PxToolBar(null);
        }
        
        public virtual AR303020_CustomerLocationMaint ReadOne(Gate gate, string BAccountID, string LocationCD)
        {
            new BiObject<AR303020_CustomerLocationMaint>(gate).ReadOne(this, BAccountID, LocationCD);
            return this;
        }
        
        public virtual AR303020_CustomerLocationMaint ReadOne(string BAccountID, string LocationCD)
        {
            return this.ReadOne(ApiConnection.Source, BAccountID, LocationCD);
        }
        
        public virtual void SyncTOC()
        {
            ToolBar.SyncTOC.Click();
        }
        
        public virtual void Note()
        {
            ToolBar.Note.Click();
        }
        
        public virtual void FilesMenuShow()
        {
            ToolBar.FilesMenuShow.Click();
        }
        
        public virtual void Custom()
        {
            ToolBar.Custom.Click();
        }
        
        public virtual void ActionSelectWorkingProject()
        {
            ToolBar.ActionSelectWorkingProject.Click();
        }
        
        public virtual void InspectElementCtrlAltClick()
        {
            ToolBar.InspectElementCtrlAltClick.Click();
        }
        
        public virtual void ManageAttributes()
        {
            ToolBar.ManageAttributes.Click();
        }
        
        public virtual void MenuEditProj()
        {
            ToolBar.MenuEditProj.Click();
        }
        
        public virtual void ManageCustomizations()
        {
            ToolBar.ManageCustomizations.Click();
        }
        
        public virtual void KeyBtnRefresh()
        {
            ToolBar.KeyBtnRefresh.Click();
        }
        
        public virtual void Help()
        {
            ToolBar.Help.Click();
        }
        
        public virtual void MenuOpener()
        {
            ToolBar.MenuOpener.Click();
        }
        
        public virtual void CancelClose()
        {
            ToolBar.CancelClose.Click();
        }
        
        public virtual void SaveClose()
        {
            ToolBar.SaveClose.Click();
        }
        
        public virtual void Save()
        {
            ToolBar.Save.Click();
        }
        
        public virtual void Cancel()
        {
            ToolBar.Cancel.Click();
        }
        
        public virtual void Insert()
        {
            ToolBar.Insert.Click();
        }
        
        public virtual void Delete()
        {
            ToolBar.Delete.Click();
        }
        
        public virtual void CopyPaste()
        {
            ToolBar.CopyPaste.Click();
        }
        
        public virtual void CopyDocument()
        {
            ToolBar.CopyDocument.Click();
        }
        
        public virtual void PasteDocument()
        {
            ToolBar.PasteDocument.Click();
        }
        
        public virtual void SaveTemplate()
        {
            ToolBar.SaveTemplate.Click();
        }
        
        public virtual void First()
        {
            ToolBar.First.Click();
        }
        
        public virtual void Previous()
        {
            ToolBar.Previous.Click();
        }
        
        public virtual void Next()
        {
            ToolBar.Next.Click();
        }
        
        public virtual void Last()
        {
            ToolBar.Last.Click();
        }
        
        public virtual void ValidateAddresses()
        {
            ToolBar.ValidateAddresses.Click();
        }
        
        public virtual void ViewAccountLocation()
        {
            ToolBar.ViewAccountLocation.Click();
        }
        
        public virtual void CasesContactViewdetails()
        {
            ToolBar.CasesContactViewdetails.Click();
        }
        
        public virtual void CustomOther()
        {
            ToolBar.CustomOther.Click();
        }
        
        public virtual void LongRun()
        {
            ToolBar.LongRun.Click();
        }
        
        public virtual void LongrunCancel()
        {
            ToolBar.LongrunCancel.Click();
        }
        
        public virtual void LongrunTimer()
        {
            ToolBar.LongrunTimer.Click();
        }
        
        public class PxToolBar : PxControlCollection
        {
            
			public ToolBarButton SyncTOC { get; }
			public ToolBarButton Note { get; }
			public ToolBarButton FilesMenuShow { get; }
			public ToolBarButton Custom { get; }
			public ToolBarButton ActionSelectWorkingProject { get; }
			public ToolBarButton InspectElementCtrlAltClick { get; }
			public ToolBarButton ManageAttributes { get; }
			public ToolBarButton MenuEditProj { get; }
			public ToolBarButton ManageCustomizations { get; }
			public ToolBarButton KeyBtnRefresh { get; }
			public ToolBarButton Help { get; }
			public ToolBarButton MenuOpener { get; }
			public ToolBarButton CancelClose { get; }
			public ToolBarButton SaveClose { get; }
			public ToolBarButton Save { get; }
			public ToolBarButton Cancel { get; }
			public ToolBarButton Insert { get; }
			public ToolBarButton Delete { get; }
			public ToolBarButton CopyPaste { get; }
			public ToolBarButton CopyDocument { get; }
			public ToolBarButton PasteDocument { get; }
			public ToolBarButton SaveTemplate { get; }
			public ToolBarButton First { get; }
			public ToolBarButton Previous { get; }
			public ToolBarButton Next { get; }
			public ToolBarButton Last { get; }
			public ToolBarButton ValidateAddresses { get; }
			public ToolBarButton ViewAccountLocation { get; }
			public ToolBarButton CasesContactViewdetails { get; }
			public ToolBarButton CustomOther { get; }
			public ToolBarButton LongRun { get; }
			public ToolBarButton LongrunCancel { get; }
			public ToolBarButton LongrunTimer { get; }
            
            public PxToolBar(string locator)
            {
                SyncTOC = new ToolBarButton("css=#ctl00_usrCaption_tlbPath div[data-cmd=\'syncTOC\']", "Sync Navigation Pane", locator, null);
                Note = new ToolBarButton("css=#ctl00_usrCaption_tlbDataView div[data-cmd=\'NoteShow\']", "Add Note", locator, null);
                FilesMenuShow = new ToolBarButton("css=#ctl00_usrCaption_tlbDataView div[data-cmd=\'FilesMenuShow\']", "Files", locator, null);
                Custom = new ToolBarButton("css=#ctl00_usrCaption_CustomizationDialogs_PXToolBar1 div[data-cmd=\'Custom\']", "Customization", locator, null);
                ActionSelectWorkingProject = new ToolBarButton("css=div#ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom li[data-cmd=\'" +
                        "ActionSelectWorkingProject\']", "Select Project...", locator, Custom);
                InspectElementCtrlAltClick = new ToolBarButton("css=div#ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom li.menuItem d" +
                        "iv:textEqual(\"Inspect Element (Ctrl+Alt+Click)\")", "Inspect Element (Ctrl+Alt+Click)", locator, Custom);
                ManageAttributes = new ToolBarButton("css=div#ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom li[data-cmd=\'" +
                        "ManageAttributes\']", "Manage User-Defined Fields", locator, Custom);
                MenuEditProj = new ToolBarButton("css=div#ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom li[data-cmd=\'" +
                        "menuEditProj\']", "Edit Project...", locator, Custom);
                ManageCustomizations = new ToolBarButton("css=div#ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom li.menuItem d" +
                        "iv:textEqual(\"Manage Customizations...\")", "Manage Customizations...", locator, Custom);
                KeyBtnRefresh = new ToolBarButton("css=#ctl00_usrCaption_tlbTools div[data-cmd=\'keyBtnRefresh\']", "Click to refresh page.", locator, null);
                Help = new ToolBarButton("css=#ctl00_usrCaption_tlbTools div[data-cmd=\'help\']", "View Tools", locator, null);
                MenuOpener = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_MenuOpener", "Menu", locator, null);
                CancelClose = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_CancelClose", "Discard Changes and Close", locator, null);
                CancelClose.ConfirmAction = () => Alert.AlertToException("Any unsaved changes will be discarded.");
                SaveClose = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_SaveClose", "Save the current record and close the screen (Ctrl+Shift+S).", locator, null);
                Save = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_Save", "Save (Ctrl+S).", locator, null);
                Cancel = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_Cancel", "Cancel (Esc)", locator, null);
                Cancel.ConfirmAction = () => Alert.AlertToException("Any unsaved changes will be discarded.");
                Insert = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_Insert", "Add New Record (Ctrl+Ins)", locator, null);
                Delete = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_Delete", "Delete (Ctrl+Del).", locator, null);
                Delete.ConfirmAction = () => Alert.AlertToException("The current Location record will be deleted.");
                CopyPaste = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_CopyPaste", "Clipboard", locator, null);
                CopyDocument = new ToolBarButton("css=[id=\'ctl00_phDS_ds_ToolBar_CopyPaste@CopyDocument\']", "CopyDocument", locator, CopyPaste);
                PasteDocument = new ToolBarButton("css=[id=\'ctl00_phDS_ds_ToolBar_CopyPaste@PasteDocument\']", "PasteDocument", locator, CopyPaste);
                SaveTemplate = new ToolBarButton("css=[id=\'ctl00_phDS_ds_ToolBar_CopyPaste@SaveTemplate\']", "SaveTemplate", locator, CopyPaste);
                First = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_First", "Go to First Record", locator, null);
                Previous = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_Previous", "Go to Previous Record (PgUp)", locator, null);
                Next = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_Next", "Go to Next Record (PgDn)", locator, null);
                Last = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_Last", "Go to Last Record", locator, null);
                ValidateAddresses = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_ValidateAddresses,#ctl00_phDS_ds_ToolBar_ValidateAddre" +
                        "sses_item", "Validate Addresses", locator, MenuOpener);
                ViewAccountLocation = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_viewAccountLocation,#ctl00_phDS_ds_ToolBar_viewAccount" +
                        "Location_item", "View Account Location", locator, MenuOpener);
                CasesContactViewdetails = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_Cases_Contact_ViewDetails,#ctl00_phDS_ds_ToolBar_Cases" +
                        "_Contact_ViewDetails_item", "View Details", locator, MenuOpener);
                CustomOther = new ToolBarButton("css=#ctl00_phDS_ds_ToolBar_CustomOther", "Other", locator, MenuOpener);
                LongRun = new ToolBarButton("css=qp-long-run", "Nothing in progress", locator, null);
                LongrunCancel = new ToolBarButton("css=#ctl00_phDS_ds_LongRun_cancel", "Cancel", locator, null);
                LongrunTimer = new ToolBarButton("css=#ctl00_phDS_ds_LongRun_timer", "Elapsed Time", locator, null);
            }
        }
        
        public class c_location_frmheader : Container
        {
            
            public PxButtonCollection Buttons;
            
			public Selector BAccountID { get; }
			public Label BAccountIDLabel { get; }
			public Selector LocationCD { get; }
			public Label LocationCDLabel { get; }
			public DropDown Status { get; }
			public Label StatusLabel { get; }
			public Label Ctl02_ { get; }
            
            public c_location_frmheader(string locator, string name) : 
                    base(locator, name)
            {
                BAccountID = new Selector("ctl00_phF_frmHeader_t0_edBAccountID", "Customer", locator, null);
                BAccountIDLabel = new Label(BAccountID);
                BAccountID.DataField = "BAccountID";
                LocationCD = new Selector("ctl00_phF_frmHeader_t0_edLocationCD", "Location ID", locator, null);
                LocationCDLabel = new Label(LocationCD);
                LocationCD.DataField = "LocationCD";
                Status = new DropDown("ctl00_phF_frmHeader_t0_edStatus", "Status", locator, null);
                StatusLabel = new Label(Status);
                Status.DataField = "Status";
                Status.Items.Add("A", "Active");
                Status.Items.Add("I", "Inactive");
                Ctl02_ = new Label("ctl00_phF_frmHeader_t1_ctl02", "No user-defined fields have been found.", locator, null);
                DataMemberName = "Location";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void BAccountIDEdit()
            {
                Buttons.BAccountIDEdit.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button BAccountIDEdit { get; }
                
                public PxButtonCollection()
                {
                    BAccountIDEdit = new Button("css=div[id=\'ctl00_phF_frmHeader_t0_edBAccountID\'] div[class=\'editBtnCont\'] > div " +
                            "> div", "BAccountIDEdit", "ctl00_phF_frmHeader");
                    BAccountIDEdit.WaitAction = Wait.WaitForNewWindowToOpen;
                }
            }
        }
        
        public class c_parameters_gridwizard : Container
        {
            
            public PxButtonCollection Buttons;
            
			public CheckBox IsDefault { get; }
			public Label IsDefaultLabel { get; }
			public CheckBox Override { get; }
			public Label OverrideLabel { get; }
			public Selector RoleName { get; }
			public Label RoleNameLabel { get; }
            
            public c_parameters_gridwizard(string locator, string name) : 
                    base(locator, name)
            {
                IsDefault = new CheckBox("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_defaultCkbx", "Is Default", locator, null);
                IsDefaultLabel = new Label(IsDefault);
                IsDefault.DataField = "IsDefault";
                Override = new CheckBox("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_overrideCkbx", "Override", locator, null);
                OverrideLabel = new Label(Override);
                Override.DataField = "Override";
                RoleName = new Selector("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_edRole", "Role Name", locator, null);
                RoleNameLabel = new Label(RoleName);
                RoleName.DataField = "RoleName";
                DataMemberName = "Parameters";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void Cancel()
            {
                Buttons.Cancel.Click();
            }
            
            public virtual void Prev()
            {
                Buttons.Prev.Click();
            }
            
            public virtual void Next()
            {
                Buttons.Next.Click();
            }
            
            public virtual void Finish()
            {
                Buttons.Finish.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button Cancel { get; }
			public Button Prev { get; }
			public Button Next { get; }
			public Button Finish { get; }
                
                public PxButtonCollection()
                {
                    Cancel = new Button("ctl00_usrCaption_shareColumnsDlg_gridWizard_cancel", "Cancel", "ctl00_usrCaption_shareColumnsDlg_gridWizard");
                    Prev = new Button("ctl00_usrCaption_shareColumnsDlg_gridWizard_prev", "Prev", "ctl00_usrCaption_shareColumnsDlg_gridWizard");
                    Next = new Button("ctl00_usrCaption_shareColumnsDlg_gridWizard_next", "Next", "ctl00_usrCaption_shareColumnsDlg_gridWizard");
                    Finish = new Button("ctl00_usrCaption_shareColumnsDlg_gridWizard_save", "Finish", "ctl00_usrCaption_shareColumnsDlg_gridWizard");
                }
            }
        }
        
        public class c_profilerinfoview_formprofiler : Container
        {
            
            public PxButtonCollection Buttons;
            
			public PXTextEdit StartText { get; }
			public Label StartTextLabel { get; }
			public PXTextEdit Started { get; }
			public Label StartedLabel { get; }
			public PXTextEdit RequestsLogged { get; }
			public Label RequestsLoggedLabel { get; }
			public Label LblPlace_ { get; }
            
            public c_profilerinfoview_formprofiler(string locator, string name) : 
                    base(locator, name)
            {
                StartText = new PXTextEdit("ctl00_usrCaption_pnlProfiler_formProfiler_lblStartText", "Start Text", locator, null);
                StartTextLabel = new Label(StartText);
                StartText.DataField = "StartText";
                Started = new PXTextEdit("ctl00_usrCaption_pnlProfiler_formProfiler_lblStartedAt", "Started", locator, null);
                StartedLabel = new Label(Started);
                Started.DataField = "Started";
                RequestsLogged = new PXTextEdit("ctl00_usrCaption_pnlProfiler_formProfiler_lblRequestsLogged", "Requests Logged", locator, null);
                RequestsLoggedLabel = new Label(RequestsLogged);
                RequestsLogged.DataField = "RequestsLogged";
                LblPlace_ = new Label("ctl00_usrCaption_pnlProfiler_formProfiler_lblPlace", "Lbl Place _", locator, null);
                DataMemberName = "ProfilerInfoView";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void BtnStartProfiler()
            {
                Buttons.BtnStartProfiler.Click();
            }
            
            public virtual void BtnStopProfiler()
            {
                Buttons.BtnStopProfiler.Click();
            }
            
            public virtual void BtnMainProfiler()
            {
                Buttons.BtnMainProfiler.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button BtnStartProfiler { get; }
			public Button BtnStopProfiler { get; }
			public Button BtnMainProfiler { get; }
                
                public PxButtonCollection()
                {
                    BtnStartProfiler = new Button("ctl00_usrCaption_pnlProfiler_formProfiler_btnStartProfiler", "btnStartProfiler", "ctl00_usrCaption_pnlProfiler_formProfiler");
                    BtnStopProfiler = new Button("ctl00_usrCaption_pnlProfiler_formProfiler_btnStopProfiler", "btnStopProfiler", "ctl00_usrCaption_pnlProfiler_formProfiler");
                    BtnMainProfiler = new Button("ctl00_usrCaption_pnlProfiler_formProfiler_btnMainProfiler", "btnMainProfiler", "ctl00_usrCaption_pnlProfiler_formProfiler");
                }
            }
        }
        
        public class c_firstselect_formactions : Container
        {
            
			public PXTextEdit Key { get; }
			public Label KeyLabel { get; }
            
            public c_firstselect_formactions(string locator, string name) : 
                    base(locator, name)
            {
                Key = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_PXSmartPanel1_FormActions_edKey", "Key", locator, null);
                KeyLabel = new Label(Key);
                Key.DataField = "Key";
                DataMemberName = "FirstSelect";
            }
        }
        
        public class c_comboboxvalues_gridcombos : Grid<c_comboboxvalues_gridcombos.c_grid_row, c_comboboxvalues_gridcombos.c_grid_header>
        {
            
            public PxToolBar ToolBar;
            
            public PxButtonCollection Buttons;
            
			public c_grid_filter FilterForm { get; }
            
            public c_comboboxvalues_gridcombos(string locator, string name) : 
                    base(locator, name)
            {
                ToolBar = new PxToolBar("ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos");
                DataMemberName = "ComboBoxValues";
                Buttons = new PxButtonCollection();
                FilterForm = new c_grid_filter("ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_fe_gf", "FilterForm");
            }
            
            public virtual void Export()
            {
                ToolBar.Export.Click();
            }
            
            public virtual void PageFirst()
            {
                ToolBar.PageFirst.Click();
            }
            
            public virtual void PagePrev()
            {
                ToolBar.PagePrev.Click();
            }
            
            public virtual void PageNext()
            {
                ToolBar.PageNext.Click();
            }
            
            public virtual void PageLast()
            {
                ToolBar.PageLast.Click();
            }
            
            public virtual void Hi()
            {
                ToolBar.Hi.Click();
            }
            
            public virtual void Close()
            {
                Buttons.Close.Click();
            }
            
            public class PxToolBar : PxControlCollection
            {
                
			public ToolBarButtonGrid Export { get; }
			public ToolBarButtonGrid PageFirst { get; }
			public ToolBarButtonGrid PagePrev { get; }
			public ToolBarButtonGrid PageNext { get; }
			public ToolBarButtonGrid PageLast { get; }
			public ToolBarButtonGrid Hi { get; }
                
                public PxToolBar(string locator)
                {
                    Export = new ToolBarButtonGrid("css=#ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_ab" +
                            "_tlb div[data-cmd=\'ExportExcel\']", "Export to Excel", locator, null);
                    PageFirst = new ToolBarButtonGrid("css=#ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_ab" +
                            "_tlb div[data-cmd=\'PageFirst\']", "Go to First Page (Ctrl+PgUp)", locator, null);
                    PagePrev = new ToolBarButtonGrid("css=#ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_ab" +
                            "_tlb div[data-cmd=\'PagePrev\']", "Go to Previous Page (PgUp)", locator, null);
                    PageNext = new ToolBarButtonGrid("css=#ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_ab" +
                            "_tlb div[data-cmd=\'PageNext\']", "Go to Next Page (PgDn)", locator, null);
                    PageLast = new ToolBarButtonGrid("css=#ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_ab" +
                            "_tlb div[data-cmd=\'PageLast\']", "Go to Last Page (Ctrl+PgDn)", locator, null);
                    Hi = new ToolBarButtonGrid("css=#ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_ab" +
                            "_tlb div[data-cmd=\'hi\']", "Hi", locator, null);
                }
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button Close { get; }
                
                public PxButtonCollection()
                {
                    Close = new Button("ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_PXButton5", "Close", "ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos");
                }
            }
            
            public class c_grid_row : GridRow
            {
                
			public PXTextEdit Value { get; }
			public PXTextEdit Description { get; }
                
                public c_grid_row(c_comboboxvalues_gridcombos grid) : 
                        base(grid)
                {
                    Value = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_ei", "Value", grid.Locator, "Value");
                    Value.DataField = "Value";
                    Description = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_ComboBoxValuesDictDialog_gridCombos_ei", "Description", grid.Locator, "Description");
                    Description.DataField = "Description";
                }
            }
            
            public class c_grid_header : GridHeader
            {
                
				public PXTextEditColumnFilter Value { get; }
				public PXTextEditColumnFilter Description { get; }
                
                public c_grid_header(c_comboboxvalues_gridcombos grid) : 
                        base(grid)
                {
                    Value = new PXTextEditColumnFilter(grid.Row.Value);
                    Description = new PXTextEditColumnFilter(grid.Row.Description);
                }
            }
        }
        
        public class c_vieweleminfo_formeleminfo : Container
        {
            
            public PxButtonCollection Buttons;
            
			public PXTextEdit AspxControl { get; }
			public Label AspxControlLabel { get; }
			public GroupBox IsComboBox { get; }
			public Label IsComboBoxLabel { get; }
			public PXTextEdit CacheType { get; }
			public Label CacheTypeLabel { get; }
			public PXTextEdit FieldName { get; }
			public Label FieldNameLabel { get; }
			public PXTextEdit ViewName { get; }
			public Label ViewNameLabel { get; }
			public PXTextEdit GraphName { get; }
			public Label GraphNameLabel { get; }
			public PXTextEdit ActionName { get; }
			public Label ActionNameLabel { get; }
			public RichTextEdit WikiTooltip { get; }
			public Label LblDescr_ { get; }
			public Label LblMore_ { get; }
            
            public c_vieweleminfo_formeleminfo(string locator, string name) : 
                    base(locator, name)
            {
                AspxControl = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_edAspxControl", "Control Type", locator, null);
                AspxControlLabel = new Label(AspxControl);
                AspxControl.DataField = "AspxControl";
                IsComboBox = new GroupBox("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_panelPXBUtton1", "Is Combo Box", locator, null);
                IsComboBoxLabel = new Label(IsComboBox);
                IsComboBox.DataField = "IsComboBox";
                CacheType = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_CacheType", "Data Class", locator, null);
                CacheTypeLabel = new Label(CacheType);
                CacheType.DataField = "CacheType";
                FieldName = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_FieldName", "Data Field", locator, null);
                FieldNameLabel = new Label(FieldName);
                FieldName.DataField = "FieldName";
                ViewName = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_ViewName", "View Name", locator, null);
                ViewNameLabel = new Label(ViewName);
                ViewName.DataField = "ViewName";
                GraphName = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_GraphName", "Business Logic", locator, null);
                GraphNameLabel = new Label(GraphName);
                GraphName.DataField = "GraphName";
                ActionName = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_ActionName", "Action Name", locator, null);
                ActionNameLabel = new Label(ActionName);
                ActionName.DataField = "ActionName";
                WikiTooltip = new RichTextEdit("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_WikiTooltip", "Wiki Tooltip", locator, null);
                LblDescr_ = new Label("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_lblDescr", "Description", locator, null);
                LblMore_ = new Label("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_lblMore", "More", locator, null);
                DataMemberName = "ViewElemInfo";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void Drop_downValues()
            {
                Buttons.Drop_downValues.Click();
            }
            
            public virtual void Customize()
            {
                Buttons.Customize.Click();
            }
            
            public virtual void Actions()
            {
                Buttons.Actions.Click();
            }
            
            public virtual void Cancel()
            {
                Buttons.Cancel.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button Drop_downValues { get; }
			public Button Customize { get; }
			public Button Actions { get; }
			public Button Cancel { get; }
                
                public PxButtonCollection()
                {
                    Drop_downValues = new Button("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_panelPXBUtton1_P" +
                            "XButton1", "Drop-down Values", "ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo");
                    Customize = new Button("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_PXButton3", "Customize", "ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo");
                    Actions = new Button("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_ButtonGraphActions", "Actions", "ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo");
                    Cancel = new Button("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_PXButton4", "Cancel", "ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo");
                }
            }
        }
        
        public class c_filterworkingproject_formnewproject : Container
        {
            
            public PxButtonCollection Buttons;
            
			public PXTextEdit NewProject { get; }
			public Label NewProjectLabel { get; }
            
            public c_filterworkingproject_formnewproject(string locator, string name) : 
                    base(locator, name)
            {
                NewProject = new PXTextEdit("ctl00_usrCaption_CustomizationDialogs_DlgNewProject_FormNewProject_edNewProject", "Project Name", locator, null);
                NewProjectLabel = new Label(NewProject);
                NewProject.DataField = "NewProject";
                DataMemberName = "FilterWorkingProject";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void Ok()
            {
                Buttons.Ok.Click();
            }
            
            public virtual void Cancel()
            {
                Buttons.Cancel.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button Ok { get; }
			public Button Cancel { get; }
                
                public PxButtonCollection()
                {
                    Ok = new Button("ctl00_usrCaption_CustomizationDialogs_DlgNewProject_DlgNewProjectButtonOk", "OK", "ctl00_usrCaption_CustomizationDialogs_DlgNewProject_FormNewProject");
                    Cancel = new Button("ctl00_usrCaption_CustomizationDialogs_DlgNewProject_DlgNewProjectButtonCancel", "Cancel", "ctl00_usrCaption_CustomizationDialogs_DlgNewProject_FormNewProject");
                }
            }
        }
        
        public class c_filterworkingproject_formselectproject : Container
        {
            
            public PxButtonCollection Buttons;
            
			public Selector Name { get; }
			public Label NameLabel { get; }
            
            public c_filterworkingproject_formselectproject(string locator, string name) : 
                    base(locator, name)
            {
                Name = new Selector("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_FormSelectProject_edWP", "Project Name", locator, null);
                NameLabel = new Label(Name);
                Name.DataField = "Name";
                DataMemberName = "FilterWorkingProject";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void Ok()
            {
                Buttons.Ok.Click();
            }
            
            public virtual void Cancel()
            {
                Buttons.Cancel.Click();
            }
            
            public virtual void New()
            {
                Buttons.New.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button Ok { get; }
			public Button Cancel { get; }
			public Button New { get; }
                
                public PxButtonCollection()
                {
                    Ok = new Button("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_SelectProjectOk", "OK", "ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_FormSelectProject");
                    Cancel = new Button("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_SelectProjectCancel", "Cancel", "ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_FormSelectProject");
                    New = new Button("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_BtnNewProject", "New...", "ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_FormSelectProject");
                }
            }
        }
        
        public class c_gridlist_gridgrid : Grid<c_gridlist_gridgrid.c_grid_row, c_gridlist_gridgrid.c_grid_header>
        {
            
            public PxToolBar ToolBar;
            
			public c_grid_filter FilterForm { get; }
            
            public c_gridlist_gridgrid(string locator, string name) : 
                    base(locator, name)
            {
                ToolBar = new PxToolBar("ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid");
                DataMemberName = "GridList";
                FilterForm = new c_grid_filter("ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_fe_gf", "FilterForm");
            }
            
            public virtual void PageFirst()
            {
                ToolBar.PageFirst.Click();
            }
            
            public virtual void PagePrev()
            {
                ToolBar.PagePrev.Click();
            }
            
            public virtual void PageNext()
            {
                ToolBar.PageNext.Click();
            }
            
            public virtual void PageLast()
            {
                ToolBar.PageLast.Click();
            }
            
            public virtual void Hi()
            {
                ToolBar.Hi.Click();
            }
            
            public class PxToolBar : PxControlCollection
            {
                
			public ToolBarButtonGrid PageFirst { get; }
			public ToolBarButtonGrid PagePrev { get; }
			public ToolBarButtonGrid PageNext { get; }
			public ToolBarButtonGrid PageLast { get; }
			public ToolBarButtonGrid Hi { get; }
                
                public PxToolBar(string locator)
                {
                    PageFirst = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_ab_tlb div[data-cmd=" +
                            "\'PageFirst\']", "Go to First Page (Ctrl+PgUp)", locator, null);
                    PagePrev = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_ab_tlb div[data-cmd=" +
                            "\'PagePrev\']", "Go to Previous Page (PgUp)", locator, null);
                    PageNext = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_ab_tlb div[data-cmd=" +
                            "\'PageNext\']", "Go to Next Page (PgDn)", locator, null);
                    PageLast = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_ab_tlb div[data-cmd=" +
                            "\'PageLast\']", "Go to Last Page (Ctrl+PgDn)", locator, null);
                    Hi = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_ab_tlb div[data-cmd=" +
                            "\'hi\']", "Hi", locator, null);
                }
            }
            
            public class c_grid_row : GridRow
            {
                
			public CheckBox Selected { get; }
			public PXTextEdit View { get; }
			public PXTextEdit Id { get; }
                
                public c_grid_row(c_gridlist_gridgrid grid) : 
                        base(grid)
                {
                    Selected = new CheckBox("ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_ef", "Included", grid.Locator, "Selected");
                    Selected.DataField = "Selected";
                    View = new PXTextEdit("ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_ei", "Table ID", grid.Locator, "View");
                    View.DataField = "View";
                    Id = new PXTextEdit("ctl00_usrCaption_shareColumnsDlg_gridWizard_p0_gridGrid_ei", "Grid ID", grid.Locator, "Id");
                    Id.DataField = "Id";
                }
            }
            
            public class c_grid_header : GridHeader
            {
                
				public CheckBoxColumnFilter Selected { get; }
				public PXTextEditColumnFilter View { get; }
				public PXTextEditColumnFilter Id { get; }
                
                public c_grid_header(c_gridlist_gridgrid grid) : 
                        base(grid)
                {
                    Selected = new CheckBoxColumnFilter(grid.Row.Selected);
                    View = new PXTextEditColumnFilter(grid.Row.View);
                    Id = new PXTextEditColumnFilter(grid.Row.Id);
                }
            }
        }
        
        public class c_userlist_usergrid : Grid<c_userlist_usergrid.c_grid_row, c_userlist_usergrid.c_grid_header>
        {
            
            public PxToolBar ToolBar;
            
			public c_grid_filter FilterForm { get; }
            
            public c_userlist_usergrid(string locator, string name) : 
                    base(locator, name)
            {
                ToolBar = new PxToolBar("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid");
                DataMemberName = "UserList";
                FilterForm = new c_grid_filter("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_fe_gf", "FilterForm");
            }
            
            public virtual void Refresh()
            {
                ToolBar.Refresh.Click();
            }
            
            public virtual void New()
            {
                ToolBar.New.Click();
            }
            
            public virtual void Delete()
            {
                ToolBar.Delete.Click();
            }
            
            public virtual void Adjust()
            {
                ToolBar.Adjust.Click();
            }
            
            public virtual void Export()
            {
                ToolBar.Export.Click();
            }
            
            public virtual void Hi()
            {
                ToolBar.Hi.Click();
            }
            
            public virtual void PageFirst()
            {
                ToolBar.PageFirst.Click();
            }
            
            public virtual void PagePrev()
            {
                ToolBar.PagePrev.Click();
            }
            
            public virtual void PageNext()
            {
                ToolBar.PageNext.Click();
            }
            
            public virtual void PageLast()
            {
                ToolBar.PageLast.Click();
            }
            
            public virtual void Hi1()
            {
                ToolBar.Hi1.Click();
            }
            
            public class PxToolBar : PxControlCollection
            {
                
			public ToolBarButtonGrid Refresh { get; }
			public ToolBarButtonGrid New { get; }
			public ToolBarButtonGrid Delete { get; }
			public ToolBarButtonGrid Adjust { get; }
			public ToolBarButtonGrid Export { get; }
			public ToolBarButtonGrid Hi { get; }
			public ToolBarButtonGrid PageFirst { get; }
			public ToolBarButtonGrid PagePrev { get; }
			public ToolBarButtonGrid PageNext { get; }
			public ToolBarButtonGrid PageLast { get; }
			public ToolBarButtonGrid Hi1 { get; }
                
                public PxToolBar(string locator)
                {
                    Refresh = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_at_tlb div[data-cmd=" +
                            "\'Refresh\']", "Refresh", locator, null);
                    New = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_at_tlb div[data-cmd=" +
                            "\'AddNew\']", "Add Row", locator, null);
                    Delete = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_at_tlb div[data-cmd=" +
                            "\'Delete\']", "Delete Row", locator, null);
                    Delete.ConfirmAction = () => Alert.AlertToException("The current {0} record will be deleted.");
                    Adjust = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_at_tlb div[data-cmd=" +
                            "\'AdjustColumns\']", "Fit to Screen", locator, null);
                    Export = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_at_tlb div[data-cmd=" +
                            "\'ExportExcel\']", "Export to Excel", locator, null);
                    Hi = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_at_tlb div[data-cmd=" +
                            "\'hi\']", "Hi", locator, null);
                    PageFirst = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ab_tlb div[data-cmd=" +
                            "\'PageFirst\']", "Go to First Page (Ctrl+PgUp)", locator, null);
                    PagePrev = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ab_tlb div[data-cmd=" +
                            "\'PagePrev\']", "Go to Previous Page (PgUp)", locator, null);
                    PageNext = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ab_tlb div[data-cmd=" +
                            "\'PageNext\']", "Go to Next Page (PgDn)", locator, null);
                    PageLast = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ab_tlb div[data-cmd=" +
                            "\'PageLast\']", "Go to Last Page (Ctrl+PgDn)", locator, null);
                    Hi1 = new ToolBarButtonGrid("css=#ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ab_tlb div[data-cmd=" +
                            "\'hi\']", "Hi", locator, null);
                }
            }
            
            public class c_grid_row : GridRow
            {
                
			public CheckBox Included { get; }
			public Selector Username { get; }
			public PXTextEdit DisplayName { get; }
			public PXTextEdit Email { get; }
			public PXTextEdit Guest { get; }
			public DropDown State { get; }
                
                public c_grid_row(c_userlist_usergrid grid) : 
                        base(grid)
                {
                    Included = new CheckBox("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ef", "Included", grid.Locator, "Included");
                    Included.DataField = "Included";
                    Username = new Selector("_ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_lv0_es", "Login", grid.Locator, "Username");
                    Username.DataField = "Username";
                    DisplayName = new PXTextEdit("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ei", "Display Name", grid.Locator, "DisplayName");
                    DisplayName.DataField = "DisplayName";
                    Email = new PXTextEdit("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ei", "Email", grid.Locator, "Email");
                    Email.DataField = "Email";
                    Guest = new PXTextEdit("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_ef", "Guest Account", grid.Locator, "Guest");
                    Guest.DataField = "Guest";
                    State = new DropDown("_ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_lv0_ec", "Status", grid.Locator, "State");
                    State.DataField = "State";
                    State.Items.Add("N", "Not Created");
                    State.Items.Add("O", "Online");
                    State.Items.Add("P", "Pending Activation");
                    State.Items.Add("D", "Disabled");
                    State.Items.Add("A", "Active");
                    State.Items.Add("L", "Temporarily Locked");
                }
            }
            
            public class c_grid_header : GridHeader
            {
                
				public CheckBoxColumnFilter Included { get; }
				public SelectorColumnFilter Username { get; }
				public PXTextEditColumnFilter DisplayName { get; }
				public PXTextEditColumnFilter Email { get; }
				public PXTextEditColumnFilter Guest { get; }
				public DropDownColumnFilter State { get; }
                
                public c_grid_header(c_userlist_usergrid grid) : 
                        base(grid)
                {
                    Included = new CheckBoxColumnFilter(grid.Row.Included);
                    Username = new SelectorColumnFilter(grid.Row.Username);
                    DisplayName = new PXTextEditColumnFilter(grid.Row.DisplayName);
                    Email = new PXTextEditColumnFilter(grid.Row.Email);
                    Guest = new PXTextEditColumnFilter(grid.Row.Guest);
                    State = new DropDownColumnFilter(grid.Row.State);
                }
            }
        }
        
        public class c_userlist_lv0 : Container
        {
            
			public Selector Es { get; }
			public Label EsLabel { get; }
			public DropDown Ec { get; }
            
            public c_userlist_lv0(string locator, string name) : 
                    base(locator, name)
            {
                Es = new Selector("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_lv0_es", "Es", locator, null);
                EsLabel = new Label(Es);
                Ec = new DropDown("ctl00_usrCaption_shareColumnsDlg_gridWizard_p1_userGrid_lv0_ec", "Ec", locator, null);
                DataMemberName = "UserList";
            }
        }
        
        public class c_locationcurrent_tab : Container
        {
            
			public PXTextEdit Descr { get; }
			public Label DescrLabel { get; }
			public CheckBox OverrideAddress { get; }
			public Label OverrideAddressLabel { get; }
			public CheckBox OverrideContact { get; }
			public Label OverrideContactLabel { get; }
			public Selector CBranchID { get; }
			public Label CBranchIDLabel { get; }
			public Selector CPriceClassID { get; }
			public Label CPriceClassIDLabel { get; }
			public Selector CDefProjectID { get; }
			public Label CDefProjectIDLabel { get; }
			public PXTextEdit TaxRegistrationID { get; }
			public Label TaxRegistrationIDLabel { get; }
			public Selector CTaxZoneID { get; }
			public Label CTaxZoneIDLabel { get; }
			public DropDown CTaxCalcMode { get; }
			public Label CTaxCalcModeLabel { get; }
			public PXTextEdit CAvalaraExemptionNumber { get; }
			public Label CAvalaraExemptionNumberLabel { get; }
			public DropDown CAvalaraCustomerUsageType { get; }
			public Label CAvalaraCustomerUsageTypeLabel { get; }
			public Selector CSiteID { get; }
			public Label CSiteIDLabel { get; }
			public Selector CCarrierID { get; }
			public Label CCarrierIDLabel { get; }
			public Selector CShipTermsID { get; }
			public Label CShipTermsIDLabel { get; }
			public Selector CShipZoneID { get; }
			public Label CShipZoneIDLabel { get; }
			public Selector CFOBPointID { get; }
			public Label CFOBPointIDLabel { get; }
			public CheckBox CResedential { get; }
			public Label CResedentialLabel { get; }
			public CheckBox CSaturdayDelivery { get; }
			public Label CSaturdayDeliveryLabel { get; }
			public CheckBox CInsurance { get; }
			public Label CInsuranceLabel { get; }
			public CheckBox CGroundCollect { get; }
			public Label CGroundCollectLabel { get; }
			public DropDown CShipComplete { get; }
			public Label CShipCompleteLabel { get; }
			public PXNumberEdit COrderPriority { get; }
			public Label COrderPriorityLabel { get; }
			public PXNumberEdit CLeadTime { get; }
			public Label CLeadTimeLabel { get; }
			public Selector CCalendarID { get; }
			public Label CCalendarIDLabel { get; }
			public DateSelector UsrWWStartSec { get; }
			public Label UsrWWStartSecLabel { get; }
			public DateSelector UsrWWEndSec { get; }
			public Label UsrWWEndSecLabel { get; }
			public CheckBox IsARAccountSameAsMain { get; }
			public Label IsARAccountSameAsMainLabel { get; }
			public Selector CSalesAcctID { get; }
			public Label CSalesAcctIDLabel { get; }
			public Selector CSalesSubID { get; }
			public Label CSalesSubIDLabel { get; }
			public Selector CDiscountAcctID { get; }
			public Label CDiscountAcctIDLabel { get; }
			public Selector CDiscountSubID { get; }
			public Label CDiscountSubIDLabel { get; }
			public Selector CFreightAcctID { get; }
			public Label CFreightAcctIDLabel { get; }
			public Selector CFreightSubID { get; }
			public Label CFreightSubIDLabel { get; }
			public Label LblPhone1_ { get; }
			public Label LblPhone2_ { get; }
			public Label LblFax_ { get; }
            
            public c_locationcurrent_tab(string locator, string name) : 
                    base(locator, name)
            {
                Descr = new PXTextEdit("ctl00_phG_tab_t0_edDescr", "Location Name", locator, null);
                DescrLabel = new Label(Descr);
                Descr.DataField = "Descr";
                OverrideAddress = new CheckBox("ctl00_phG_tab_t0_chkOverrideAddress", "Override", locator, null);
                OverrideAddressLabel = new Label(OverrideAddress);
                OverrideAddress.DataField = "OverrideAddress";
                OverrideContact = new CheckBox("ctl00_phG_tab_t0_chkOverrideContact", "Override", locator, null);
                OverrideContactLabel = new Label(OverrideContact);
                OverrideContact.DataField = "OverrideContact";
                CBranchID = new Selector("ctl00_phG_tab_t0_edCBranchID", "Default Branch", locator, null);
                CBranchIDLabel = new Label(CBranchID);
                CBranchID.DataField = "CBranchID";
                CPriceClassID = new Selector("ctl00_phG_tab_t0_edCPriceClassID", "Price Class", locator, null);
                CPriceClassIDLabel = new Label(CPriceClassID);
                CPriceClassID.DataField = "CPriceClassID";
                CDefProjectID = new Selector("ctl00_phG_tab_t0_edCDefProjectID", "Default Project", locator, null);
                CDefProjectIDLabel = new Label(CDefProjectID);
                CDefProjectID.DataField = "CDefProjectID";
                TaxRegistrationID = new PXTextEdit("ctl00_phG_tab_t1_edTaxRegistrationID", "Tax Registration ID", locator, null);
                TaxRegistrationIDLabel = new Label(TaxRegistrationID);
                TaxRegistrationID.DataField = "TaxRegistrationID";
                CTaxZoneID = new Selector("ctl00_phG_tab_t1_edCTaxZoneID", "Tax Zone", locator, null);
                CTaxZoneIDLabel = new Label(CTaxZoneID);
                CTaxZoneID.DataField = "CTaxZoneID";
                CTaxCalcMode = new DropDown("ctl00_phG_tab_t1_edTaxCalcMode", "Tax Calculation Mode", locator, null);
                CTaxCalcModeLabel = new Label(CTaxCalcMode);
                CTaxCalcMode.DataField = "CTaxCalcMode";
                CTaxCalcMode.Items.Add("T", "Tax Settings");
                CTaxCalcMode.Items.Add("G", "Gross");
                CTaxCalcMode.Items.Add("N", "Net");
                CAvalaraExemptionNumber = new PXTextEdit("ctl00_phG_tab_t1_edCAvalaraExemptionNumber", "Tax Exemption Number", locator, null);
                CAvalaraExemptionNumberLabel = new Label(CAvalaraExemptionNumber);
                CAvalaraExemptionNumber.DataField = "CAvalaraExemptionNumber";
                CAvalaraCustomerUsageType = new DropDown("ctl00_phG_tab_t1_edCAvalaraCustomerUsageType", "Entity Usage Type", locator, null);
                CAvalaraCustomerUsageTypeLabel = new Label(CAvalaraCustomerUsageType);
                CAvalaraCustomerUsageType.DataField = "CAvalaraCustomerUsageType";
                CAvalaraCustomerUsageType.Items.Add("A", "Federal Government");
                CAvalaraCustomerUsageType.Items.Add("B", "State/Local Govt.");
                CAvalaraCustomerUsageType.Items.Add("C", "Tribal Government");
                CAvalaraCustomerUsageType.Items.Add("D", "Foreign Diplomat");
                CAvalaraCustomerUsageType.Items.Add("E", "Charitable Organization");
                CAvalaraCustomerUsageType.Items.Add("F", "Religious");
                CAvalaraCustomerUsageType.Items.Add("G", "Resale");
                CAvalaraCustomerUsageType.Items.Add("H", "Agricultural Production");
                CAvalaraCustomerUsageType.Items.Add("I", "Industrial Prod/Mfg.");
                CAvalaraCustomerUsageType.Items.Add("J", "Direct Pay Permit");
                CAvalaraCustomerUsageType.Items.Add("K", "Direct Mail");
                CAvalaraCustomerUsageType.Items.Add("L", "Other");
                CAvalaraCustomerUsageType.Items.Add("M", "Education");
                CAvalaraCustomerUsageType.Items.Add("N", "Local Government");
                CAvalaraCustomerUsageType.Items.Add("P", "Commercial Aquaculture");
                CAvalaraCustomerUsageType.Items.Add("Q", "Commercial Fishery");
                CAvalaraCustomerUsageType.Items.Add("R", "Non-resident");
                CAvalaraCustomerUsageType.Items.Add("0", "Default");
                CSiteID = new Selector("ctl00_phG_tab_t1_edCSiteID", "Warehouse", locator, null);
                CSiteIDLabel = new Label(CSiteID);
                CSiteID.DataField = "CSiteID";
                CCarrierID = new Selector("ctl00_phG_tab_t1_edCarrierID", "Ship Via", locator, null);
                CCarrierIDLabel = new Label(CCarrierID);
                CCarrierID.DataField = "CCarrierID";
                CShipTermsID = new Selector("ctl00_phG_tab_t1_edShipTermsID", "Shipping Terms", locator, null);
                CShipTermsIDLabel = new Label(CShipTermsID);
                CShipTermsID.DataField = "CShipTermsID";
                CShipZoneID = new Selector("ctl00_phG_tab_t1_edShipZoneID", "Shipping Zone", locator, null);
                CShipZoneIDLabel = new Label(CShipZoneID);
                CShipZoneID.DataField = "CShipZoneID";
                CFOBPointID = new Selector("ctl00_phG_tab_t1_edFOBPointID", "FOB Point", locator, null);
                CFOBPointIDLabel = new Label(CFOBPointID);
                CFOBPointID.DataField = "CFOBPointID";
                CResedential = new CheckBox("ctl00_phG_tab_t1_chkResedential", "Residential Delivery", locator, null);
                CResedentialLabel = new Label(CResedential);
                CResedential.DataField = "CResedential";
                CSaturdayDelivery = new CheckBox("ctl00_phG_tab_t1_chkSaturdayDelivery", "Saturday Delivery", locator, null);
                CSaturdayDeliveryLabel = new Label(CSaturdayDelivery);
                CSaturdayDelivery.DataField = "CSaturdayDelivery";
                CInsurance = new CheckBox("ctl00_phG_tab_t1_chkInsurance", "Insurance", locator, null);
                CInsuranceLabel = new Label(CInsurance);
                CInsurance.DataField = "CInsurance";
                CGroundCollect = new CheckBox("ctl00_phG_tab_t1_chkGroundCollect", "FedEx Ground Collect", locator, null);
                CGroundCollectLabel = new Label(CGroundCollect);
                CGroundCollect.DataField = "CGroundCollect";
                CShipComplete = new DropDown("ctl00_phG_tab_t1_edCShipComplete", "Shipping Rule", locator, null);
                CShipCompleteLabel = new Label(CShipComplete);
                CShipComplete.DataField = "CShipComplete";
                CShipComplete.Items.Add("C", "Ship Complete");
                CShipComplete.Items.Add("B", "Back Order Allowed");
                CShipComplete.Items.Add("L", "Cancel Remainder");
                COrderPriority = new PXNumberEdit("ctl00_phG_tab_t1_edCOrderPriority", "Order Priority", locator, null);
                COrderPriorityLabel = new Label(COrderPriority);
                COrderPriority.DataField = "COrderPriority";
                CLeadTime = new PXNumberEdit("ctl00_phG_tab_t1_edLeadTime", "Lead Time (Days)", locator, null);
                CLeadTimeLabel = new Label(CLeadTime);
                CLeadTime.DataField = "CLeadTime";
                CCalendarID = new Selector("ctl00_phG_tab_t1_edCalendar", "Calendar", locator, null);
                CCalendarIDLabel = new Label(CCalendarID);
                CCalendarID.DataField = "CCalendarID";
                UsrWWStartSec = new DateSelector("ctl00_phG_tab_t1_CstPXDateTimeEdit2", "Time Window Start", locator, null);
                UsrWWStartSecLabel = new Label(UsrWWStartSec);
                UsrWWStartSec.DataField = "UsrWWStartSec";
                UsrWWEndSec = new DateSelector("ctl00_phG_tab_t1_CstPXDateTimeEdit1", "Time Window End", locator, null);
                UsrWWEndSecLabel = new Label(UsrWWEndSec);
                UsrWWEndSec.DataField = "UsrWWEndSec";
                IsARAccountSameAsMain = new CheckBox("ctl00_phG_tab_t2_chkIsARAccountSameAsMain", "Same As Default Location\'s", locator, null);
                IsARAccountSameAsMainLabel = new Label(IsARAccountSameAsMain);
                IsARAccountSameAsMain.DataField = "IsARAccountSameAsMain";
                CSalesAcctID = new Selector("ctl00_phG_tab_t2_edCSalesAcctID", "Sales Account", locator, null);
                CSalesAcctIDLabel = new Label(CSalesAcctID);
                CSalesAcctID.DataField = "CSalesAcctID";
                CSalesSubID = new Selector("ctl00_phG_tab_t2_edCSalesSubID", "Sales Sub.", locator, null);
                CSalesSubIDLabel = new Label(CSalesSubID);
                CSalesSubID.DataField = "CSalesSubID";
                CDiscountAcctID = new Selector("ctl00_phG_tab_t2_edCDiscountAcctID", "Discount Account", locator, null);
                CDiscountAcctIDLabel = new Label(CDiscountAcctID);
                CDiscountAcctID.DataField = "CDiscountAcctID";
                CDiscountSubID = new Selector("ctl00_phG_tab_t2_edCDiscountSubID", "Discount Sub.", locator, null);
                CDiscountSubIDLabel = new Label(CDiscountSubID);
                CDiscountSubID.DataField = "CDiscountSubID";
                CFreightAcctID = new Selector("ctl00_phG_tab_t2_edCFreightAcctID", "Freight Account", locator, null);
                CFreightAcctIDLabel = new Label(CFreightAcctID);
                CFreightAcctID.DataField = "CFreightAcctID";
                CFreightSubID = new Selector("ctl00_phG_tab_t2_edCFreightSubID", "Freight Sub.", locator, null);
                CFreightSubIDLabel = new Label(CFreightSubID);
                CFreightSubID.DataField = "CFreightSubID";
                LblPhone1_ = new Label("ctl00_phG_tab_t0_Contact_lblPhone1", "Lbl Phone 1_", locator, null);
                LblPhone2_ = new Label("ctl00_phG_tab_t0_Contact_lblPhone2", "Lbl Phone 2_", locator, null);
                LblFax_ = new Label("ctl00_phG_tab_t0_Contact_lblFax", "Lbl Fax _", locator, null);
                DataMemberName = "LocationCurrent";
            }
        }
        
        public class c_address_address : Container
        {
            
            public PxButtonCollection Buttons;
            
			public PXTextEdit AddressLine1 { get; }
			public Label AddressLine1Label { get; }
			public PXTextEdit AddressLine2 { get; }
			public Label AddressLine2Label { get; }
			public PXTextEdit City { get; }
			public Label CityLabel { get; }
			public Selector State { get; }
			public Label StateLabel { get; }
			public PXTextEdit PostalCode { get; }
			public Label PostalCodeLabel { get; }
			public Selector CountryID { get; }
			public Label CountryIDLabel { get; }
			public PXNumberEdit Latitude { get; }
			public Label LatitudeLabel { get; }
			public PXNumberEdit Longitude { get; }
			public Label LongitudeLabel { get; }
			public CheckBox IsValidated { get; }
			public Label IsValidatedLabel { get; }
            
            public c_address_address(string locator, string name) : 
                    base(locator, name)
            {
                AddressLine1 = new PXTextEdit("ctl00_phG_tab_t0_Address_edAddressLine1", "Address Line 1", locator, null);
                AddressLine1Label = new Label(AddressLine1);
                AddressLine1.DataField = "AddressLine1";
                AddressLine2 = new PXTextEdit("ctl00_phG_tab_t0_Address_edAddressLine2", "Address Line 2", locator, null);
                AddressLine2Label = new Label(AddressLine2);
                AddressLine2.DataField = "AddressLine2";
                City = new PXTextEdit("ctl00_phG_tab_t0_Address_edCity", "City", locator, null);
                CityLabel = new Label(City);
                City.DataField = "City";
                State = new Selector("ctl00_phG_tab_t0_Address_edState", "State", locator, null);
                StateLabel = new Label(State);
                State.DataField = "State";
                PostalCode = new PXTextEdit("ctl00_phG_tab_t0_Address_edPostalCode", "Postal Code", locator, null);
                PostalCodeLabel = new Label(PostalCode);
                PostalCode.DataField = "PostalCode";
                CountryID = new Selector("ctl00_phG_tab_t0_Address_edCountryID", "Country", locator, null);
                CountryIDLabel = new Label(CountryID);
                CountryID.DataField = "CountryID";
                Latitude = new PXNumberEdit("ctl00_phG_tab_t0_Address_edLatitude", "Latitude", locator, null);
                LatitudeLabel = new Label(Latitude);
                Latitude.DataField = "Latitude";
                Longitude = new PXNumberEdit("ctl00_phG_tab_t0_Address_edLongitude", "Longitude", locator, null);
                LongitudeLabel = new Label(Longitude);
                Longitude.DataField = "Longitude";
                IsValidated = new CheckBox("ctl00_phG_tab_t0_Address_edIsValidated", "Validated", locator, null);
                IsValidatedLabel = new Label(IsValidated);
                IsValidated.DataField = "IsValidated";
                DataMemberName = "Address";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void AddressLookup()
            {
                Buttons.AddressLookup.Click();
            }
            
            public virtual void ViewonMap()
            {
                Buttons.ViewonMap.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button AddressLookup { get; }
			public Button ViewonMap { get; }
                
                public PxButtonCollection()
                {
                    AddressLookup = new Button("ctl00_phG_tab_t0_Address_btnAddressLookup", "Address Lookup", "ctl00_phG_tab_t0_Address");
                    ViewonMap = new Button("ctl00_phG_tab_t0_Address_btnViewMainOnMap", "View on Map", "ctl00_phG_tab_t0_Address");
                }
            }
        }
        
        public class c_contact_contact : Container
        {
            
            public PxButtonCollection Buttons;
            
			public PXTextEdit FullName { get; }
			public Label FullNameLabel { get; }
			public PXTextEdit Attention { get; }
			public Label AttentionLabel { get; }
			public DropDown Phone1Type { get; }
			public Label Phone1TypeLabel { get; }
			public PXTextEdit Phone1 { get; }
			public Label Phone1Label { get; }
			public DropDown Phone2Type { get; }
			public Label Phone2TypeLabel { get; }
			public PXTextEdit Phone2 { get; }
			public Label Phone2Label { get; }
			public DropDown FaxType { get; }
			public Label FaxTypeLabel { get; }
			public PXTextEdit Fax { get; }
			public Label FaxLabel { get; }
			public EmailEdit EMail { get; }
			public Label EMailLabel { get; }
			public LinkEdit WebSite { get; }
			public Label WebSiteLabel { get; }
			public Label LblPhone1_ { get; }
			public Label LblPhone2_ { get; }
			public Label LblFax_ { get; }
            
            public c_contact_contact(string locator, string name) : 
                    base(locator, name)
            {
                FullName = new PXTextEdit("ctl00_phG_tab_t0_Contact_edFullName", "Account Name", locator, null);
                FullNameLabel = new Label(FullName);
                FullName.DataField = "FullName";
                Attention = new PXTextEdit("ctl00_phG_tab_t0_Contact_edAttention", "Attention", locator, null);
                AttentionLabel = new Label(Attention);
                Attention.DataField = "Attention";
                Phone1Type = new DropDown("ctl00_phG_tab_t0_Contact_Phone1Type", "Phone 1 Type", locator, null);
                Phone1TypeLabel = new Label(Phone1Type);
                Phone1Type.DataField = "Phone1Type";
                Phone1Type.Items.Add("B1", "Business 1");
                Phone1Type.Items.Add("B2", "Business 2");
                Phone1Type.Items.Add("B3", "Business 3");
                Phone1Type.Items.Add("C", "Cell");
                Phone1Type.Items.Add("BA1", "Assistant");
                Phone1Type.Items.Add("BF", "Fax");
                Phone1Type.Items.Add("H1", "Home");
                Phone1Type.Items.Add("HF", "Home Fax");
                Phone1 = new PXTextEdit("ctl00_phG_tab_t0_Contact_PXMaskEdit1", "Phone 1", locator, null);
                Phone1Label = new Label(Phone1);
                Phone1.DataField = "Phone1";
                Phone2Type = new DropDown("ctl00_phG_tab_t0_Contact_Phone2Type", "Phone 2 Type", locator, null);
                Phone2TypeLabel = new Label(Phone2Type);
                Phone2Type.DataField = "Phone2Type";
                Phone2Type.Items.Add("B1", "Business 1");
                Phone2Type.Items.Add("B2", "Business 2");
                Phone2Type.Items.Add("B3", "Business 3");
                Phone2Type.Items.Add("C", "Cell");
                Phone2Type.Items.Add("BA1", "Assistant");
                Phone2Type.Items.Add("BF", "Fax");
                Phone2Type.Items.Add("H1", "Home");
                Phone2Type.Items.Add("HF", "Home Fax");
                Phone2 = new PXTextEdit("ctl00_phG_tab_t0_Contact_PXMaskEdit2", "Phone 2", locator, null);
                Phone2Label = new Label(Phone2);
                Phone2.DataField = "Phone2";
                FaxType = new DropDown("ctl00_phG_tab_t0_Contact_FaxType", "Fax Type", locator, null);
                FaxTypeLabel = new Label(FaxType);
                FaxType.DataField = "FaxType";
                FaxType.Items.Add("B1", "Business 1");
                FaxType.Items.Add("B2", "Business 2");
                FaxType.Items.Add("B3", "Business 3");
                FaxType.Items.Add("C", "Cell");
                FaxType.Items.Add("BA1", "Assistant");
                FaxType.Items.Add("BF", "Fax");
                FaxType.Items.Add("H1", "Home");
                FaxType.Items.Add("HF", "Home Fax");
                Fax = new PXTextEdit("ctl00_phG_tab_t0_Contact_PXMaskEdit3", "Fax", locator, null);
                FaxLabel = new Label(Fax);
                Fax.DataField = "Fax";
                EMail = new EmailEdit("ctl00_phG_tab_t0_Contact_edEMail", "Email", locator, null);
                EMailLabel = new Label(EMail);
                EMail.DataField = "EMail";
                WebSite = new LinkEdit("ctl00_phG_tab_t0_Contact_edWebSite", "Web", locator, null);
                WebSiteLabel = new Label(WebSite);
                WebSite.DataField = "WebSite";
                LblPhone1_ = new Label("ctl00_phG_tab_t0_Contact_lblPhone1", "Lbl Phone 1_", locator, null);
                LblPhone2_ = new Label("ctl00_phG_tab_t0_Contact_lblPhone2", "Lbl Phone 2_", locator, null);
                LblFax_ = new Label("ctl00_phG_tab_t0_Contact_lblFax", "Lbl Fax _", locator, null);
                DataMemberName = "Contact";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void AddressLookup()
            {
                Buttons.AddressLookup.Click();
            }
            
            public virtual void ViewonMap()
            {
                Buttons.ViewonMap.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button AddressLookup { get; }
			public Button ViewonMap { get; }
                
                public PxButtonCollection()
                {
                    AddressLookup = new Button("ctl00_phG_tab_t0_Address_btnAddressLookup", "Address Lookup", "ctl00_phG_tab_t0_Contact");
                    ViewonMap = new Button("ctl00_phG_tab_t0_Address_btnViewMainOnMap", "View on Map", "ctl00_phG_tab_t0_Contact");
                }
            }
        }
        
        public class c_araccountsublocation_araccountsublocation : Container
        {
            
			public Selector CARAccountID { get; }
			public Label CARAccountIDLabel { get; }
			public Selector CARSubID { get; }
			public Label CARSubIDLabel { get; }
            
            public c_araccountsublocation_araccountsublocation(string locator, string name) : 
                    base(locator, name)
            {
                CARAccountID = new Selector("ctl00_phG_tab_t2_ARAccountSubLocation_edCARAccountID", "AR Account", locator, null);
                CARAccountIDLabel = new Label(CARAccountID);
                CARAccountID.DataField = "CARAccountID";
                CARSubID = new Selector("ctl00_phG_tab_t2_ARAccountSubLocation_edCARSubID", "AR Sub.", locator, null);
                CARSubIDLabel = new Label(CARSubID);
                CARSubID.DataField = "CARSubID";
                DataMemberName = "ARAccountSubLocation";
            }
        }
        
        public class c_araccountsublocation_araccountsublocation1 : Container
        {
            
			public Selector CRetainageAcctID { get; }
			public Label CRetainageAcctIDLabel { get; }
			public Selector CRetainageSubID { get; }
			public Label CRetainageSubIDLabel { get; }
            
            public c_araccountsublocation_araccountsublocation1(string locator, string name) : 
                    base(locator, name)
            {
                CRetainageAcctID = new Selector("ctl00_phG_tab_t2_ARAccountSubLocation1_edRetainageAcctID", "Retainage Receivable Account", locator, null);
                CRetainageAcctIDLabel = new Label(CRetainageAcctID);
                CRetainageAcctID.DataField = "CRetainageAcctID";
                CRetainageSubID = new Selector("ctl00_phG_tab_t2_ARAccountSubLocation1_edRetainageSubID", "Retainage Receivable Sub.", locator, null);
                CRetainageSubIDLabel = new Label(CRetainageSubID);
                CRetainageSubID.DataField = "CRetainageSubID";
                DataMemberName = "ARAccountSubLocation";
            }
        }
        
        public class c_addresslookupfilter_addresslookuppanelformaddress : Container
        {
            
            public PxButtonCollection Buttons;
            
			public PXTextEdit SearchAddress { get; }
			public Label SearchAddressLabel { get; }
			public PXTextEdit ViewName { get; }
			public Label ViewNameLabel { get; }
			public PXTextEdit AddressLine1 { get; }
			public Label AddressLine1Label { get; }
			public PXTextEdit AddressLine2 { get; }
			public Label AddressLine2Label { get; }
			public PXTextEdit AddressLine3 { get; }
			public Label AddressLine3Label { get; }
			public PXTextEdit City { get; }
			public Label CityLabel { get; }
			public PXTextEdit CountryID { get; }
			public Label CountryIDLabel { get; }
			public PXTextEdit State { get; }
			public Label StateLabel { get; }
			public PXTextEdit PostalCode { get; }
			public Label PostalCodeLabel { get; }
			public PXTextEdit Latitude { get; }
			public Label LatitudeLabel { get; }
			public PXTextEdit Longitude { get; }
			public Label LongitudeLabel { get; }
            
            public c_addresslookupfilter_addresslookuppanelformaddress(string locator, string name) : 
                    base(locator, name)
            {
                SearchAddress = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_searchBox", "Search Address", locator, null);
                SearchAddressLabel = new Label(SearchAddress);
                SearchAddress.DataField = "SearchAddress";
                ViewName = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_addressLookupViewName", "ViewName", locator, null);
                ViewNameLabel = new Label(ViewName);
                ViewName.DataField = "ViewName";
                AddressLine1 = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponseAddressL" +
                        "ine1", "AddressLine1", locator, null);
                AddressLine1Label = new Label(AddressLine1);
                AddressLine1.DataField = "AddressLine1";
                AddressLine2 = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponseAddressL" +
                        "ine2", "AddressLine2", locator, null);
                AddressLine2Label = new Label(AddressLine2);
                AddressLine2.DataField = "AddressLine2";
                AddressLine3 = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponseAddressL" +
                        "ine3", "AddressLine3", locator, null);
                AddressLine3Label = new Label(AddressLine3);
                AddressLine3.DataField = "AddressLine3";
                City = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponseCity", "City", locator, null);
                CityLabel = new Label(City);
                City.DataField = "City";
                CountryID = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponseCountry", "CountryID", locator, null);
                CountryIDLabel = new Label(CountryID);
                CountryID.DataField = "CountryID";
                State = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponseState", "State", locator, null);
                StateLabel = new Label(State);
                State.DataField = "State";
                PostalCode = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponsePostalCo" +
                        "de", "PostalCode", locator, null);
                PostalCodeLabel = new Label(PostalCode);
                PostalCode.DataField = "PostalCode";
                Latitude = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponseLatitude" +
                        "", "Latitude", locator, null);
                LatitudeLabel = new Label(Latitude);
                Latitude.DataField = "Latitude";
                Longitude = new PXTextEdit("ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress_SearchResponseLongitud" +
                        "e", "Longitude", locator, null);
                LongitudeLabel = new Label(Longitude);
                Longitude.DataField = "Longitude";
                DataMemberName = "AddressLookupFilter";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void Select()
            {
                Buttons.Select.Click();
            }
            
            public virtual void Cancel()
            {
                Buttons.Cancel.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button Select { get; }
			public Button Cancel { get; }
                
                public PxButtonCollection()
                {
                    Select = new Button("ctl00_phG_AddressLookupPanel_AddressLookupSelectAction", "Select", "ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress");
                    Cancel = new Button("ctl00_phG_AddressLookupPanel_AddressEntityBtnCancel", "Cancel", "ctl00_phG_AddressLookupPanel_AddressLookupPanelformAddress");
                }
            }
        }
        
        public class c_filterpreview_formpreview : Container
        {
            
            public PxButtonCollection Buttons;
            
            public c_filterpreview_formpreview(string locator, string name) : 
                    base(locator, name)
            {
                DataMemberName = "FilterPreview";
                Buttons = new PxButtonCollection();
            }
            
            public virtual void Ok()
            {
                Buttons.Ok.Click();
            }
            
            public virtual void Cancel()
            {
                Buttons.Cancel.Click();
            }
            
            public class PxButtonCollection : PxControlCollection
            {
                
			public Button Ok { get; }
			public Button Cancel { get; }
                
                public PxButtonCollection()
                {
                    Ok = new Button("ctl00_usrCaption_PanelDynamicForm_PXButtonOK", "OK", "ctl00_usrCaption_PanelDynamicForm_FormPreview");
                    Cancel = new Button("ctl00_usrCaption_PanelDynamicForm_PXButtonCancel", "Cancel", "ctl00_usrCaption_PanelDynamicForm_FormPreview");
                }
            }
        }
        
        public class c_attributes : Container
        {
            
            public c_attributes(string locator, string name) : 
                    base(locator, name)
            {
                DataMemberName = null;
            }
        }
    }
}
